### ISSUE TITLE
Unable to submit a comment via Touchpoints

### ISSUE THREAD

**Issue by suzchapUSDS** [usds/techfar-hub-website-v3#52]
From home page, selected feedback tab, selected yes, wrote in a comment and clicked submit. 

Got error alert box "Error submission request made from non-authorized host".

Using Chrome on mac.

![image](https://user-images.githubusercontent.com/80708288/213532954-3da25bbd-f676-4ab0-add2-047ff07cb119.png)

**Comment by mattbowen-usds** [comment]
Good catch! Updated on the Touchpoints side
