### ISSUE TITLE
HTML tag needs lang attribute

### ISSUE THREAD

**Issue by louiseClarkUSDS** [usds/techfar-hub-website-v3#55]
### Accessibility Issue

In order to meet WCAG 2.0 Level A requirement ["3.1.1 Language of the Page"](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#qr-meaning-doc-lang-id) the html tag needs a language attribute. 

### Why it matters?

When a web page’s primary language is programmatically identified, browsers and assistive technologies can render the text more accurately; screen readers can use the correct pronunciation; visual browsers can display the correct characters; media players can show captions correctly; and automated translation is enabled.

### How to fix

1.  Identify the page’s primary language.
2. Choose the corresponding a language code from the [IANA Language Subtag Registry](http://www.iana.org/assignments/language-subtag-registry) - In this case it would be "en" for English
3. Add a lang attribute to the <html> element using the correct language tag for the value that represents the primary language of the page.
4. If a lang attribute is already specified, make sure its value is spelled correctly.

**Comment by mattbowen-usds** [comment]
This was resolved in PR #58
