### ISSUE TITLE
List items need a parent element

### ISSUE THREAD

**Issue by louiseClarkUSDS** [usds/techfar-hub-website-v3#56]
### Accessibility Issue

In order to meet WCAG 2.0 Level A Success Criteria 1.3.1 ["Info and Relationships"](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html), the step indicator on the ["Get Started" ](https://techfarhub.usds.gov/get-started/)page must have a parent element wrapping the `<li>` elements.

### Why It Matters

When an assistive technology encounters a list that’s poorly structured, it might respond in an unexpected way. As a result, people who use assistive technologies might find it difficult to interpret the list. When list items are contained in an appropriate parent element element, assistive technologies can interpret the list consistently.

### How to Fix

All `<li>` elements must be contained by a `<ul>`, `<ol>`, or `<menu>` parent element.

For each list item ( `<li> `element):
- Enclose the `<li>` element in a `<ul>` or `<ol>` element (or in a parent element with role="list" ).
- Don’t use a role attribute to override the native semantics of the `<ul>` or `<ol>` element.

**Comment by mattbowen-usds** [comment]
This was resolved in PR #58
