### ISSUE TITLE
Invalid Case Study Link

### ISSUE THREAD

**Issue by SunilManchikantiUSDS** [usds/techfar-hub-website-v3#92]
On [this](https://techfarhub.usds.gov/resources/case-studies/) page, the Read More link button for the _Agile Government and The Department of Justice_ case study is invalid and seems to forward to bakerology.com.

<img width="1216" alt="image" src="https://github.com/usds/techfar-hub-website-v3/assets/137526618/828640d9-4181-4e81-af31-fac012ed05b8">

**Comment by KevinWehmuellerUSDS** [comment]
Resolved via PR #95
